### ISSUE TITLE
[Suggestion] Add info about how some things work

### ISSUE THREAD

**Issue by Macintosh-Fan** [hewlett-packard-lovecraft/sane-dnf-config-generator#1]
I'm a bit of a noob to how these things work, but could you explain how certain parameters work (info button thing)? Or, link to a website that explains it all?

**Comment by hewlett-packard-lovecraft** [comment]
Thanks for the star!

Good idea. I'll add some info and a link to the dnf documentation.

**Comment by Macintosh-Fan** [comment]
Done yet or soon?
