### ISSUE TITLE
Can't connect to website (Nov 7, 2021 @ 18:47 PST)

### ISSUE THREAD

**Issue by Macintosh-Fan** [hewlett-packard-lovecraft/sane-dnf-config-generator#2]
Is your machine down?
![image](https://user-images.githubusercontent.com/50642934/140676427-7e561926-7149-41a5-9856-84ef155a321a.png)

**Comment by hewlett-packard-lovecraft** [comment]
Thanks for the heads up! I moved my virtual machine to a different VLAN a week ago and I didn't notice that this broke the website

**Comment by Macintosh-Fan** [comment]
Do you think you'll have the website up soon?

**Comment by hewlett-packard-lovecraft** [comment]
website is up
